# Generated by Django 5.0.4 on 2024-04-30 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningpath',
            name='date',
        ),
        migrations.RemoveField(
            model_name='learningpath',
            name='progress',
        ),
        migrations.AddField(
            model_name='learningpath',
            name='duration',
            field=models.IntegerField(default=1000),
        ),
    ]
