# Generated by Django 5.0.4 on 2024-04-30 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_remove_learningpath_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningpath',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
